joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

joint_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: joint_l1
  pid:
    p: 1
    i: 0
    d: 1